// packages/react/src/components/PageBuilder.tsx
import React, { useEffect, useRef } from 'react';
import { PageBuilder } from '@mindfiredigital/page-builder-core/dist/PageBuilder.js';

export interface PageBuilderReactProps {
  onInitialize?: (pageBuilder: PageBuilder) => void;
  customStyles?: {
    wrapper?: React.CSSProperties;
    sidebar?: React.CSSProperties;
    canvas?: React.CSSProperties;
    customization?: React.CSSProperties;
  };
}

export const PageBuilderReact: React.FC<PageBuilderReactProps> = ({ 
  onInitialize,
  customStyles = {}
}) => {
  const pageBuilderRef = useRef<PageBuilder | null>(null);
  const wrapperRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Function to set up the DOM structure
    const setupDOMStructure = () => {
      if (!wrapperRef.current) return;

      // Clear existing content
      wrapperRef.current.innerHTML = '';

      // Create the main app container
      const appDiv = document.createElement('div');
      appDiv.id = 'app';

      // Create required inner elements
      appDiv.innerHTML = 
      `
        <div id="sidebar"></div>
        <div id="canvas" class="canvas"></div>
        <div id="customization">
          <h4 id="component-name">Component: None</h4>
          <div id="controls"></div>
          <div id="layers-view" class="hidden"></div>
        </div>
        <div id="notification" class="notification hidden"></div>
        <div id="dialog" class="dialog hidden">
          <div class="dialog-content">
            <p id="dialog-message"></p>
            <button id="dialog-yes" class="dialog-btn">Yes</button>
            <button id="dialog-no" class="dialog-btn">No</button>
          </div>
        </div>`
      ;

      wrapperRef.current.appendChild(appDiv);
    };

    // Initialize PageBuilder after DOM setup
    const initializePageBuilder = () => {
      try {
        if (!pageBuilderRef.current) {
          setupDOMStructure();

          // Create new PageBuilder instance
          const pageBuilder = new PageBuilder();
          pageBuilderRef.current = pageBuilder;

          if (onInitialize) {
            onInitialize(pageBuilder);
          }

          // Trigger DOMContentLoaded to initialize PageBuilder
          const event = new Event('DOMContentLoaded');
          document.dispatchEvent(event);
        }
      } catch (error) {
        console.error('Error initializing PageBuilder:', error);
      }
    };

    // Small delay to ensure React has finished rendering
    setTimeout(initializePageBuilder, 0);

    return () => {
      pageBuilderRef.current = null;
    };
  }, [onInitialize]);

  return (
    <div 
      ref={wrapperRef}
      style={{ 
        margin: 'auto', 
        width: '100%', 
        height: '100%',
        ...customStyles.wrapper 
      }}
    />
  );
}

// packages/web-component/src/components/PageBuilder.ts
import { PageBuilder } from '@mindfiredigital/page-builder-core/dist/PageBuilder.js';

export class PageBuilderComponent extends HTMLElement {
  private pageBuilder!: PageBuilder;
  private initialized = false;

  constructor() {
    super();

    // Set up inner HTML structure
    this.innerHTML = `
      <div id="app">
        <div id="sidebar"></div>
        <div id="canvas" class="canvas"></div>
        <div id="customization">
          <h4 id="component-name">Component: None</h4>
          <div id="controls"></div>
          <div id="layers-view" class="hidden"></div>
        </div>
        <div id="notification" class="notification hidden"></div>
        <div id="dialog" class="dialog hidden">
          <div class="dialog-content">
            <p id="dialog-message"></p>
            <button id="dialog-yes" class="dialog-btn">Yes</button>
            <button id="dialog-no" class="dialog-btn">No</button>
          </div>
        </div>
      </div>
    `;
  }

  connectedCallback() {
    if (this.initialized) return;

    // Use MutationObserver to ensure DOM elements are ready
    const observer = new MutationObserver((mutations, obs) => {
      const appElement = this.querySelector('#app');
      if (appElement) {
        this.initializePageBuilder();
        obs.disconnect(); // Stop observing once initialized
        this.initialized = true;
      }
    });

    observer.observe(this, {
      childList: true,
      subtree: true,
    });
  }

  private initializePageBuilder() {
    try {
      this.pageBuilder = new PageBuilder();

      // Wait for next frame to ensure DOM is ready
      requestAnimationFrame(() => {
        if (typeof this.pageBuilder.setupInitialComponents === 'function') {
          this.pageBuilder.setupInitialComponents();
          console.log('✅ PageBuilder initialized successfully');
        } else {
          console.error('❌ setupInitialComponents is not a function');
        }
      });
    } catch (error) {
      console.error('❌ Failed to initialize PageBuilder:', error);
    }
  }

  disconnectedCallback() {
    // Cleanup when component is removed
    this.initialized = false;
    console.log('❌ PageBuilderComponent disconnected from the DOM');
  }
}

// Register the custom element
if (!customElements.get('page-builder')) {
  customElements.define('page-builder', PageBuilderComponent);
  console.log('✅ Custom element "page-builder" registered');
}
